name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    if: github.event_name == 'pull_request' || !(github.event_name == 'push' && github.ref == 'refs/heads/main')
    outputs:
      branch: ${{ steps.set_branch_variable.outputs.branch }}
    runs-on: ubuntu-latest
    steps:
      - id: set_branch_variable
        name: Set Branch Variable
        uses: emmahsax/github-actions/set-branch-variable@main

  go-release:
    needs: [setup]
    uses: emmahsax/github-actions/.github/workflows/go-test.yml@add_go_test_action
    with:
      branch: ${{ needs.setup.outputs.branch }}
