name: Go

on:
  create:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    outputs:
      branch: ${{ steps.set_branch_variable.outputs.branch }}
    runs-on: ubuntu-latest
    steps:
      - id: set_branch_variable
        name: Set Branch Variable
        uses: emmahsax/github-actions/set-branch-variable@main

  go-test:
    needs: [setup]
    uses: emmahsax/github-actions/.github/workflows/go-test.yml@main
    with:
      branch: ${{ needs.setup.outputs.branch }}

  tag-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tag - ${{ github.ref }}"
      - run: echo "event name - ${{ github.event_name }}"
