name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        go_version:  ["1.20.x", "1.21.x"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: emmahsax/github-actions/setup-go@main
      with:
        github_token: ${{ secrets.github_token }}
        go_version: ${{ matrix.go_versionv }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - run: go vet ./...

    - uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-path: ./
        gofmt-flags: '-l -d'

    - uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2022.1.3"
        install-go: false
        cache-key: ${{ matrix.go_version }}
        working-directory: ./
