name: Go

on:
  # push:
  #   branches: [ main ]
  #   tags: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    outputs:
      branch: ${{ steps.set_branch_variable.outputs.branch }}
    runs-on: ubuntu-latest
    steps:
      - id: set_branch_variable
        name: Set Branch Variable
        uses: emmahsax/github-actions/set-branch-variable@main

  go-test:
    needs: [setup]
    uses: emmahsax/github-actions/.github/workflows/go-test.yml@main
    with:
      branch: ${{ needs.setup.outputs.branch }}

  go-release:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: emmahsax/github-actions/.github/workflows/go-release.yml@main
    with:
      tag_name: ${{ github.ref_name }}
      upload: false
