name: Check Line Change in PR

on:
  pull_request:

env:
  description: version update
  file: main.go
  addition_regex: ^\+.+fmt.Println\(.+\)
  removal_regex: ^\-.+fmt.Println\(.+\)

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: -1

      - id: changes
        name: Check for Changes
        run: |
          changed_file="$(git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} ${{ env.file }})"
          if [ -z "$changed_file" ]; then
            exit 1
          else
            changed_line=$(echo "$changed_file" | grep -E '${{ env.addition_regex }}')
            if [[ -n "$changed_line" ]]; then
              removal_line=$(echo "$changed_file" | grep -E '${{ env.removal_regex }}')
              echo "addition_changes=$changed_line" >> $GITHUB_OUTPUT
              echo "removal_changes=$removal_line" >> $GITHUB_OUTPUT
            else
              exit 1
            fi
          fi

      - if: success()
        name: Found Change Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: changes
          message: |
            :white_check_mark: Found ${{ env.description }} in `${{ env.file }}`:

            ```diff
            ${{ steps.changes.outputs.removal_changes }}
            ${{ steps.changes.outputs.addition_changes }}
            ```

      - if: failure()
        name: Missing Change Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: changes
          message: |
            :warning: Could not find ${{ env.description }} in `${{ env.file }}`
