name: Check Line Change in PR

on:
  pull_request:

jobs:
  check_line_change:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: -1

      - name: Check line change
        id: line_change
        run: |
          changed_file="$(git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} main.go)"
          if [ -z "$changed_file" ]; then
            echo "line_changed=false" >> $GITHUB_OUTPUT
          else
            echo $changed_file
            changed_lines=$(echo $changed_file | grep -E '^\+.+fmt.Println\(.+\)')
            echo $changed_lines
            if [[ -n "$changed_lines" ]]; then
              echo "line_changed=true" >> $GITHUB_OUTPUT
            else
              echo "line_changed=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Display result
        run: |
          echo "Line changed: ${{ steps.line_change.outputs.line_changed }}"
