name: Release
run-name: Release ${{ inputs.tag_name }}
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: The tag name to make a GitHub Release for
        required: true
        type: string

jobs:
  go-release:
    uses: emmahsax/github-actions/.github/workflows/go-release.yml@try-to-add-tag-name-output
    with:
      tag_name: ${{ inputs.tag_name }}
