name: Test Title
# run-name: Release ${{ git rev-parse --short ${{ github.sha }} }}

on:
  workflow_dispatch:
    inputs:
      tag_name:
        default: ""
        description: The tag name to make a GitHub Release for
        required: false
        type: string

jobs:
  setup:
    outputs:
      tag_name: ${{ steps.tag_name.outputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Set Tag Name
        id: tag_name
        run: |
          if [[ "${{ inputs.tag_name }}" == "" ]]; then
            echo "tag_name=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${{ inputs.tag_name }}" >> $GITHUB_OUTPUT
          fi

  go-release:
    needs: [ setup ]
    uses: emmahsax/github-actions/.github/workflows/go-release.yml@try-to-add-tag-name-output
    with:
      build_command: go build
      tag_name: ${{ needs.setup.outputs.tag_name }}
      upload: false
