name: Test Title

on:
  workflow_dispatch:
    inputs:
      tag_name:
        default: ""
        description: The tag name to make a GitHub Release for
        required: false
        type: string

jobs:
  go-release:
    uses: emmahsax/github-actions/.github/workflows/go-release.yml@try-to-add-tag-name-output
    with:
      build_command: go build
      tag_name: ${{ inputs.tag_name }}
      upload: false

  set-run-name:
    needs: [ go-release ]
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.github_token }}" \
            -d '{"name": "Release ${{ needs.go-release.outputs.tag_name }}"}' \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}"
