name: Test Title
# run-name: Release ${{ git rev-parse --short ${{ github.sha }} }}

on:
  workflow_dispatch:
    inputs:
      tag_name:
        default: ""
        description: The tag name to make a GitHub Release for
        required: false
        type: string

jobs:
  go-release:
    uses: emmahsax/github-actions/.github/workflows/go-release.yml@try-to-add-tag-name-output
    with:
      build_command: go build
      tag_name: ${{ inputs.tag_name }}
      upload: false

  set-run-name:
    needs: [ go-release ]
    runs-on: ubuntu-latest
    steps:
      - name: Set Run Name
        id: set_run_name
        run: |
          gh run view ${{ github.run_id }} --log --json | \
            jq -r '.name' | \
            sed -e "s/^Test Title\(.*\)$/Release ${{ needs.go-release.outputs.tag_name }}/g" | \
            xargs -I {} gh run watch ${{ github.run_id }} --name {}
